build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

artifacts:
  - path: minerva_author.zip
    name: MinervaAuthor

install:
  # Issues have been encountered with installing numpy and scipy on
  # AppVeyor e.g.
  # http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
  # Miniconda is recommended as the way to install these. See also:
  # https://github.com/appveyor/ci/issues/359
  # The following adopts approaches suggested in the above links.
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% nomkl"
  - activate test-environment

  # Majority of dependencies can be installed with Anaconda
  - conda install -c conda-forge "numpy>=1.18" "matplotlib==3.2.2" cython

  - pip install -r requirements.txt

  - conda install zarr

build_script:
  - pyinstaller -F --paths $env:CONDA_PREFIX --hidden-import="pkg_resources.py2_warn" --add-data "static;static" --add-data "minerva-story;minerva-story" --icon icon.ico --name minerva_author src/app.py

after_build:
  - 7z a minerva_author.zip dist
